# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 595b9d9e4c0f9001f14b209aa809428885c0f37762380dea5104c036c503865dd1d570baf0510a271db03d12f87f98eb86006056454f5f2e48cf8d5b4fe5c4f9

test:
  secret_key_base: 72e3a54bd1a6079ea1f8e4762ace499b0a5e9ad0626aa352f1de56b7cc8542bb0777c0364e2282cfd5f9023976837adf9f41953aa861349d30d7a69e8fbb762d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
